version: "3.4"

services:
  identifier:
    image: semtech/mu-identifier:1.8.1
    links:
      - dispatcher:dispatcher
    ports:
      - "80:80"
  dispatcher:
    image: semtech/mu-dispatcher:1.1.2
    links:
      - resource:resource
    volumes:
      - ./config/dispatcher:/config

  db:
    image: tenforce/virtuoso:1.3.2-virtuoso7.2.2
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
    ports:
      - "8890:8890"
    volumes:
      - ./data/db:/data
      - ./config/virtuoso/virtuoso.ini:/data/virtuoso.ini
  migrations:
    image: semtech/mu-migrations-service
    links:
      - db:database
    volumes:
      - ./config/migrations:/data/migrations
  resource:
    image: semtech/mu-cl-resources:1.18.0
    links:
      - db:database
    volumes:
      - ./config/resources:/config
    labels:
      - "logging"
  authorization:
    image: semtech/mu-authorization
    links:
      - db:database
      - deltanotifier:deltanotifier
    volumes:
      - ./config/authorization:/config
    environment:
      LOG_DELTA_CLIENT_COMMUNICATION: "true"
      LOG_DELTA_MESSAGES: "true"
  deltanotifier:
    image: semtech/mu-delta-notifier
    volumes:
      - ./config/delta:/config
    environment:
      LOG_SERVER_CONFIGURATION: "true"
      DEBUG_DELTA_SEND: "true"
      DEBUG_DELTA_MATCH: "true"
